name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ninja build tools etc.
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'
      - name: Install flutter project dependencies
        run: flutter pub get
      #- run: flutter test
      - name: Build Android application
        run: |
          flutter build apk
          flutter build appbundle
      - name: Build Linux application
        run: flutter build linux
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mopicon-apk-latest
          retention-days: 1
          path: build/app/outputs/flutter-apk/*
      - name: Upload appbundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: mopicon-appbundle-latest
          retention-days: 1
          path: build/app/outputs/bundle/release/*
      - name: Upload Linux executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: mopicon-linux-x64-latest
          retention-days: 1
          path: build/linux/x64/release/bundle/**
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/outputs/flutter-apk/*
